# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1777a1bba196d056aa52202484ae85501fb3b34cd18fd4ec23bba0e587a9d05581dfc69f2ea4689ea4d218e0d665516bd097e6ca5e0e854f407a82794ce43dfd

test:
  secret_key_base: e37ad555e4917e04c71a9a7cee8c4137ee09410e5dc020408bb36bbd96c619a6bfebdef7ee42ec66b3d6fcd9472a49466f572678c3de41b0f5b46e40497318f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
